# Generated by Django 4.0.2 on 2022-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('start_at', models.CharField(max_length=255)),
                ('end_at', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'Yopiq'), (1, 'Ochiq')], default=1)),
                ('stol', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
