# Generated by Django 4.0.2 on 2022-02-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_order_id_order_restaurant_remove_order_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
